version: "3.7"

networks: 
  mynetwork:
    name: mynetwork
    attachable: true    

services:
  
  postgres:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      networks:
       - mynetwork

        
  keycloak:
    image: jboss/keycloak:7.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
      KEYCLOAK_FRONTEND_URL: http://linux.machine.com:3333
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 3333:8080
    depends_on:
      - postgres
    networks:
      - mynetwork


  openresty:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: resty
    image: resty
    links:
      - keycloak
    ports:
      - "80:80"
      - "8081:8081"
      - "8082:8082"
    networks:
      - mynetwork
    restart: always
    volumes:
      - "./nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./nginx/html/:/opt/nginx/html"
volumes:
    postgres_data:
        external: true
